[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[env.production]
  [env.production.build.environment]
    NODE_VERSION = "24.17.0"
    NPM_VERSION = "11.13.0"
